---
- name: reload zones
  command: rndc reload
  when:
    - ansible_virtualization_type != "docker" or dns_ignore_docker

- name: reload configuration
  command: rndc reload
  when:
    - ansible_virtualization_type != "docker" or dns_ignore_docker
